export const TILE_WIDTH = 63;
export const TILE_HEIGHT = 38;
export const TILE_HEIGHT_OFFSET = 8;
export const TILE_HEIGHT_OFFSET_RATIO = 8 / TILE_HEIGHT;
export const CAMERA_ZOOM = 20;
export const CAMERA_X = 5;
export const CAMERA_Y = 3;
export const CANVAS_WIDTH = 640;
export const CANVAS_HEIGHT = 400;